name: mcgee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  audioplayers: ^6.8.1
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  camera: ^0.11.2+1
  camera_windows: ^0.2.6+5
  flutter_svg: ^2.3.0
  image: ^4.5.4
  narration_engine:
    path: packages/narration_engine
  path_provider: ^2.1.6
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - binoculars-icon.svg
    - lib/assets/MCgEe.svg
    - lib/assets/logo.svg
    - lib/assets/morgan-avatar.webp
    - lib/assets/david-avatar.webp
    - lib/assets/eve-avatar.webp
    - lib/assets/switch.mp3
